/* 
 * Copyright 2015 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.nbgames.yaya;

import org.nbgames.core.NbGames;
import org.nbgames.core.base.GameTopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

@ActionID(
        category = "Game/Dice",
        id = "org.nbgames.yaya.YayaAction"
)
@ConvertAsProperties(
        dtd = "-//org.nbgames.yaya//Yaya//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "YayaTopComponent",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@TopComponent.OpenActionRegistration(
        displayName = "#Game-Name",
        preferredID = "YayaTopComponent"
)
/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public final class YayaTopComponent extends GameTopComponent {

    private final YayaController mGameController;

    public YayaTopComponent() {
        super();
        mBundle = NbBundle.getBundle(this.getClass());
        mGameName = mBundle.getString("Game-Name");
        initComponents();
        setName(mGameName);
        mGameController = new YayaController(this);
        NbGames.outln(NbGames.LOG_TITLE, mGameName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        mGameController.requestNewGame();
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }

    @Override
    protected void componentDeactivated() {
        super.componentDeactivated();
        setActionCategoryVisible("Yaya", false);
    }

    @Override
    protected void componentActivated() {
        super.componentActivated();
        setActionCategoryVisible("Yaya", true);

        try {
            mGameController.updateStatusBar();
        } catch (Exception e) {
        }
    }
}
